### ISSUE TITLE
MOTD is blocked for dead players

### ISSUE THREAD

**Issue by Rainyan** [Rainyan/sourcemod-nt-fadefix#11]
As reported from Discord. Should verify if this is fadefix specific bug.

**Comment by bauxiteDYS** [comment]
Tested it a bit and as far as I can tell, it is the fadefix plugin that blocks the MOTD panel.

**Comment by Rainyan** [comment]
**edit**: This was a problem of myself having a bad test server.

---

I can't reproduce this bug. Tested with plugin version 0.5.7 ([9a282ce](https://github.com/Rainyan/sourcemod-nt-fadefix/commit/9a282ce4ae2dad823d03f590271d6ff07575e265)) and latest nt_competitive.

To trigger the MOTD panel:
```sp
#include <sourcemod>

public void OnPluginStart()
{
    ShowMOTDPanel(1, "foo", "bar", MOTDPANEL_TYPE_TEXT);
}
```

Then `sm plugins reload motd` (or whatever you called the test plugin), whilst in the fade view.

Produces:
![20240103152325_1](https://github.com/Rainyan/sourcemod-nt-fadefix/assets/6595066/8cb92b01-420d-498f-94e7-3a0482522abd)

which to me looks like it's working as intended(?)

**Comment by bauxiteDYS** [comment]
Are you using your own MOTD plugin? The FadeFix plugin seems to block the default Sourcemod MOTD panel. Video to demonstrate: Includes the list of plugins being used. I think you can reproduce just by using default SM plugins + Comp plugin 2.1.0 + FadeFix 0.5.7, when dead during a live game, the FadeFix plugin will block attempts to view the MOTD by using the !motd command. If mp_forcecamera is not enabled or FadeFix is unloaded then it works as normal.

Uploading 2024-01-03 19-08-52.mp4…
